
import { GoogleGenAI, GenerateImagesResponse, GenerateContentResponse, GeneratedImage } from "@google/genai";
import { ExportMimeType } from '../types'; // Removed AspectRatioValue import

export interface GeneratedImageResult {
  base64Image: string;
  mimeType: ExportMimeType;
}

export const generateImageApi = async (
  prompt: string,
  // aspectRatio: string, // This was AspectRatioValue - REMOVED
  outputMimeType: ExportMimeType,
  apiKey: string | null
): Promise<GeneratedImageResult> => {
  if (!apiKey) {
    throw new Error("API Key is not configured. Please enter your API Key.");
  }

  const ai = new GoogleGenAI({ apiKey });

  try {
    const response: GenerateImagesResponse = await ai.models.generateImages({
      model: 'imagen-3.0-generate-002',
      prompt: prompt,
      config: { 
        numberOfImages: 1,
        outputMimeType: outputMimeType,
        // aspectRatio: aspectRatio as AspectRatioValue, // REMOVED
      },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const image: GeneratedImage = response.generatedImages[0];
      if (image.image && image.image.imageBytes && image.image.mimeType) {
        return {
          base64Image: image.image.imageBytes,
          mimeType: image.image.mimeType as ExportMimeType 
        };
      } else if (image.image && image.image.imageBytes && (image as any).outputMimeType) {
         return {
          base64Image: image.image.imageBytes,
          mimeType: (image as any).outputMimeType as ExportMimeType
        };
      }
      else {
        throw new Error("Generated image data or its mimeType is missing.");
      }
    } else {
      throw new Error("No images were generated by the API.");
    }
  } catch (error) {
    console.error('Error calling Gemini API for image generation:', error);
    if (error instanceof Error) {
        const geminiError = error as any; // Cast to any to access potential specific properties
        const errorMessage = geminiError.message || '';

        if (errorMessage.includes("Imagen API is only accessible to billed users")) {
            throw new Error("Image generation failed: The Imagen API (model: 'imagen-3.0-generate-002') may require a billed Google Cloud account. Please check your Google Cloud project's billing status and ensure the 'Vertex AI API' (which includes Imagen services) is enabled and your API key has permissions for it.");
        }
        if (errorMessage.includes("API key not valid") || errorMessage.includes("API_KEY_INVALID")) {
             throw new Error("Invalid API Key. Please check your Google API Key and ensure it has the necessary permissions for the Vertex AI API (Imagen).");
        }
        if (errorMessage.includes("quota")) {
            throw new Error("API quota exceeded. Please check your Google Cloud project quotas for the Vertex AI API.");
        }
         throw new Error(`Gemini API error: ${errorMessage}`);
    }
    throw new Error("An unknown error occurred while generating the image.");
  }
};

export const generateTextApi = async (prompt: string, apiKey: string | null): Promise<string> => {
  if (!apiKey) {
    throw new Error("API Key is not configured. Please enter your API Key.");
  }
  
  const ai = new GoogleGenAI({ apiKey });

  try {
    const response: GenerateContentResponse = await ai.models.generateContent({
      model: 'gemini-2.5-flash-preview-04-17',
      contents: prompt,
    });
    return response.text;
  } catch (error) {
    console.error('Error calling Gemini API for text generation:', error);
    if (error instanceof Error) {
        const geminiError = error as any;
        const errorMessage = geminiError.message || '';
         if (errorMessage.includes("API key not valid") || errorMessage.includes("API_KEY_INVALID")) {
             throw new Error("Invalid API Key for text generation. Please check your Google API Key.");
        }
        throw new Error(`Gemini API error for text generation: ${errorMessage}`);
    }
    throw new Error("An unknown error occurred while generating text.");
  }
};
